In [1]:
import numpy as np
import pandas as pd
from statsmodels.tsa.arima.model import ARIMA

In [3]:
data=pd.read_csv("continuous dataset.csv")
data

,datetime,nat_demand,T2M_toc,QV2M_toc,TQL_toc,W2M_toc,T2M_san,QV2M_san,TQL_san,W2M_san,T2M_dav,QV2M_dav,TQL_dav,W2M_dav,Holiday_ID,holiday,school
0,2015-01-03 01:00:00,970.3450,25.865259,0.018576,0.016174,21.850546,23.482446,0.017272,0.001855,10.328949,22.662134,0.016562,0.096100,5.364148,0.0,0.0,0.0
1,2015-01-03 02:00:00,912.1755,25.899255,0.018653,0.016418,22.166944,23.399255,0.017265,0.001327,10.681517,22.578943,0.016509,0.087646,5.572471,0.0,0.0,0.0
2,2015-01-03 03:00:00,900.2688,25.937280,0.018768,0.015480,22.454911,23.343530,0.017211,0.001428,10.874924,22.531030,0.016479,0.078735,5.871184,0.0,0.0,0.0
3,2015-01-03 04:00:00,889.9538,25.957544,0.018890,0.016273,22.110481,23.238794,0.017128,0.002599,10.518620,22.512231,0.016487,0.068390,5.883621,0.0,0.0,0.0
4,2015-01-03 05:00:00,893.6865,25.973840,0.018981,0.017281,21.186089,23.075403,0.017059,0.001729,9.733589,22.481653,0.016456,0.064362,5.611724,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14425,2016-08-26 02:00:00,926.3750,25.819177,0.018486,0.060272,5.548931,24.303552,0.018631,0.120483,5.543168,22.631677,0.017479,0.169983,4.444457,0.0,0.0,1.0
14426,2016-08-26 03:00:00,898.5478,25.821619,0.018387,0.051895,5.231911,24.243494,0.018563,0.098969,5.957362,22.555994,0.017327,0.166687,4.498469,0.0,0.0,1.0
14427,2016-08-26 04:00:00,891.5739,25.838647,0.018303,0.044601,5.041622,24.198022,0.018456,0.087860,6.183355,22.494897,0.017174,0.157593,4.583638,0.0,0.0,1.0
14428,2016-08-26 05:00:00,921.1532,25.842584,0.018227,0.047958,4.827720,24.092584,0.018296,0.089050,5.500910,22.405084,0.017006,0.118530,4.516351,0.0,0.0,1.0
14429,2016-08-26 06:00:00,929.0331,25.958948,0.018296,0.059189,4.256931,24.193323,0.018311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14430 entries, 0 to 14429
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   datetime    14430 non-null  object
 1   nat_demand  14430 non-null  float64
 2   T2M_toc     14430 non-null  float64
 3   QV2M_toc    14430 non-null  float64
 4   TQL_toc     14430 non-null  float64
 5   W2M_toc     14430 non-null  float64
 6   T2M_san     14430 non-null  float64
 7   QV2M_san    14430 non-null  float64
 8   TQL_san     14429 non-null  float64
 9   W2M_san     14429 non-null  float64
 10  T2M_dav     14429 non-null  float64
 11  QV2M_dav    14429 non-null  float64
 12  TQL_dav     14429 non-null  float64
 13  W2M_dav     14429 non-null  float64
 14  Holiday_ID  14429 non-null  float64
 15  holiday     14429 non-null  float64
 16  school      14429 non-null  float64
dtypes: float64(16), object(1)
memory usage: 1.9+ MB

In [5]:
data.columns

Index(['datetime', 'nat_demand', 'T2M_toc', 'QV2M_toc', 'TQL_toc', 'W2M_toc',
       'T2M_san', 'QV2M_san', 'TQL_san', 'W2M_san', 'T2M_dav', 'QV2M_dav',
       'TQL_dav', 'W2M_dav', 'Holiday_ID', 'holiday', 'school'],
      dtype='object')

In [7]:
data['date']=pd.to_datetime(data['datetime'])
data['date']

0       2015-01-03 01:00:00
1       2015-01-03 02:00:00
2       2015-01-03 03:00:00
3       2015-01-03 04:00:00
4       2015-01-03 05:00:00
                ...
14425   2016-08-26 02:00:00
14426   2016-08-26 03:00:00
14427   2016-08-26 04:00:00
14428   2016-08-26 05:00:00
14429   2016-08-26 06:00:00
Name: date, Length: 14430, dtype: datetime64[ns]

In [8]:
data=data.sort_values('datetime')
data

,datetime,nat_demand,T2M_toc,QV2M_toc,TQL_toc,W2M_toc,T2M_san,QV2M_san,TQL_san,W2M_san,T2M_dav,QV2M_dav,TQL_dav,W2M_dav,Holiday_ID,holiday,school,date
0,2015-01-03 01:00:00,970.3450,25.865259,0.018576,0.016174,21.850546,23.482446,0.017272,0.001855,10.328949,22.662134,0.016562,0.096100,5.364148,0.0,0.0,0.0,2015-01-03 01:00:00
1,2015-01-03 02:00:00,912.1755,25.899255,0.018653,0.016418,22.166944,23.399255,0.017265,0.001327,10.681517,22.578943,0.016509,0.087646,5.572471,0.0,0.0,0.0,2015-01-03 02:00:00
2,2015-01-03 03:00:00,900.2688,25.937280,0.018768,0.015480,22.454911,23.343530,0.017211,0.001428,10.874924,22.531030,0.016479,0.078735,5.871184,0.0,0.0,0.0,2015-01-03 03:00:00
3,2015-01-03 04:00:00,889.9538,25.957544,0.018890,0.016273,22.110481,23.238794,0.017128,0.002599,10.518620,22.512231,0.016487,0.068390,5.883621,0.0,0.0,0.0,2015-01-03 04:00:00
4,2015-01-03 05:00:00,893.6865,25.973840,0.018981,0.017281,21.186089,23.075403,0.017059,0.001729,9.733589,22.481653,0.016456,0.064362,5.611724,0.0,0.0,0.0,2015-01-03 05:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14425,2016-08-26 02:00:00,926.3750,25.819177,0.018486,0.060272,5.548931,24.303552,0.018631,0.120483,5.543168,22.631677,0.017479,0.169983,4.444457,0.0,0.0,1.0,2016-08-26 02:00:00
14426,2016-08-26 03:00:00,898.5478,25.821619,0.018387,0.051895,5.231911,24.243494,0.018563,0.098969,5.957362,22.555994,0.017327,0.166687,4.498469,0.0,0.0,1.0,2016-08-26 03:00:00
14427,2016-08-26 04:00:00,891.5739,25.838647,0.018303,0.044601,5.041622,24.198022,0.018456,0.087860,6.183355,22.494897,0.017174,0.157593,4.583638,0.0,0.0,1.0,2016-08-26 04:00:00
14428,2016-08-26 05:00:00,921.1532,25.842584,0.018227,0.047958,4.827720,24.092584,0.018296,0.089050,5.500910,22.405084,0.017006,0.118530,4.516351,0.0,0.0,1.0,2016-08-26 05:00:00
14429,2016-08-26 06:00:00,929.0331,25.958948,0.018296,0.059189,4.256931,24.193323,0.018311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-08-26 06:00:00

In [15]:
datas=data['T2M_toc']

In [19]:
model=ARIMA(datas,order=(3,1,1))
model_fit=model.fit()
forecast=model_fit.forecast(steps=3)

In [20]:
print("Day 1:", forecast.iloc[0])
print("Day 2:", forecast.iloc[1])
print("Day 3:", forecast.iloc[2])

Day 1: 26.122250227358084
Day 2: 26.279294523896073
Day 3: 26.408260573817856