In [17]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder

In [20]:
data=pd.read_csv("real_drug_dataset.csv")
data

,Patient_ID,Age,Gender,Condition,Drug_Name,Dosage_mg,Treatment_Duration_days,Side_Effects,Improvement_Score
0,P0001,56,Male,Infection,Ciprofloxacin,50,9,Nausea,8.5
1,P0002,69,Male,Hypertension,Metoprolol,500,24,Tiredness,8.7
2,P0003,46,Female,Depression,Bupropion,100,25,Dry mouth,5.4
3,P0004,32,Male,Diabetes,Glipizide,850,44,Low blood sugar,6.4
4,P0005,60,Male,Depression,Bupropion,850,35,Anxiety,5.3
...,...,...,...,...,...,...,...,...,...
995,P0996,18,Male,Hypertension,Losartan,100,44,Headache,7.7
996,P0997,35,Female,Infection,Azithromycin,50,15,Nausea,5.3
997,P0998,49,Female,Depression,Sertraline,850,52,Dry mouth,8.0
998,P0999,64,Male,Depression,Escitalopram,850,36,Nausea,7.6
999,P1000,66,Female,Hypertension,Metoprolol,500,58,Tiredness,6.5

In [21]:
data.shape

(1000, 9)

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Patient_ID               1000 non-null   object
 1   Age                      1000 non-null   int64
 2   Gender                   1000 non-null   object
 3   Condition                1000 non-null   object
 4   Drug_Name                1000 non-null   object
 5   Dosage_mg                1000 non-null   int64
 6   Treatment_Duration_days  1000 non-null   int64
 7   Side_Effects             1000 non-null   object
 8   Improvement_Score        1000 non-null   float64
dtypes: float64(1), int64(3), object(5)
memory usage: 70.4+ KB

In [23]:
data.describe()

               Age    Dosage_mg  Treatment_Duration_days  Improvement_Score
count  1000.000000  1000.000000               1000.00000        1000.000000
mean     49.857000   352.650000                 32.38000           7.015200
std      18.114267   295.419617                 15.69809           1.425609
min      18.000000    50.000000                  5.00000           2.500000
25%      35.000000   100.000000                 19.00000           6.100000
50%      50.000000   250.000000                 32.00000           7.000000
75%      66.000000   500.000000                 46.00000           8.000000
max      79.000000   850.000000                 59.00000          10.000000

In [24]:
data.isnull().sum()

Patient_ID                 0
Age                        0
Gender                     0
Condition                  0
Drug_Name                  0
Dosage_mg                  0
Treatment_Duration_days    0
Side_Effects               0
Improvement_Score          0
dtype: int64

In [25]:
le=LabelEncoder()

In [27]:
data['Condition']=le.fit_transform(data['Condition'])
data['Condition']

0      3
1      2
2      0
3      1
4      0
      ..
995    2
996    3
997    0
998    0
999    2
Name: Condition, Length: 1000, dtype: int64

In [28]:
data["Drug_Name"]=le.fit_transform(data["Drug_Name"])
data["Drug_Name"]

0       4
1      11
2       3
3       6
4       3
       ..
995     9
996     2
997    13
998     5
999    11
Name: Drug_Name, Length: 1000, dtype: int64

In [33]:
x=data[['Age','Drug_Name']]
y=data[['Condition']]

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [35]:
model=GaussianNB()
model.fit(x_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianNB()

In [36]:
y_pred=model.predict(x_test)
y_pred

array([1, 1, 4, 4, 3, 3, 3, 3, 1, 2, 0, 3, 4, 3, 3, 4, 1, 3, 4, 3, 1, 1,
       1, 3, 4, 3, 3, 3, 4, 1, 1, 4, 3, 3, 1, 0, 3, 3, 3, 3, 1, 3, 1, 4,
       1, 1, 3, 4, 1, 3, 2, 1, 3, 1, 1, 3, 3, 3, 4, 1, 4, 1, 3, 1, 4, 3,
       4, 3, 4, 4, 1, 2, 3, 3, 4, 3, 4, 3, 3, 3, 3, 3, 1, 4, 4, 1, 0, 3,
       1, 4, 3, 1, 3, 4, 1, 4, 3, 3, 3, 1, 1, 1, 3, 1, 4, 1, 3, 3, 4, 0,
       1, 1, 4, 2, 4, 0, 4, 3, 4, 0, 3, 3, 1, 3, 3, 3, 1, 1, 4, 1, 1, 3,
       3, 1, 0, 3, 1, 4, 3, 2, 3, 4, 3, 1, 4, 4, 1, 1, 3, 1, 4, 1, 4, 1,
       3, 1, 1, 1, 1, 3, 3, 4, 3, 3, 4, 3, 1, 4, 3, 3, 1, 3, 1, 4, 1, 4,
       4, 2, 3, 4, 3, 4, 4, 4, 1, 3, 3, 1, 2, 4, 3, 4, 1, 2, 3, 1, 1, 4,
       1, 4])

In [37]:
new=[[43,11]]
prediction=model.predict(new)
prediction

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

array([4])